-- -----------------------------------------------------
-- Enum type "shop_unit_type"
-- -----------------------------------------------------
--create types
DO ' DECLARE BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = ''shop_unit_type'') THEN
            CREATE TYPE shop_unit_type AS ENUM(''OFFER'', ''CATEGORY'');
    END IF;
END; ' LANGUAGE plpgsql;
DROP CAST IF EXISTS (character varying AS shop_unit_type);
CREATE CAST (character varying AS shop_unit_type) WITH INOUT AS ASSIGNMENT;

-- -----------------------------------------------------
-- Table "shop_unit"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS shop_unit (
    shop_unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id UUID UNIQUE,
    name VARCHAR(1024) NOT NULL,
    date TIMESTAMP NOT NULL,
    parent_id UUID,
    shop_unit_parent_id BIGINT REFERENCES shop_unit(shop_unit_id) ON DELETE CASCADE,
    unit_type shop_unit_type NOT NULL,
    price BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS shop_unit_index_id ON shop_unit(id);

-- -----------------------------------------------------
-- Extension for tree in PostgreSQL
-- -----------------------------------------------------
CREATE EXTENSION IF NOT EXISTS ltree;

-- -----------------------------------------------------
-- Table "shop_unit_tree"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS shop_unit_tree (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id BIGINT UNIQUE NOT NULL REFERENCES shop_unit(shop_unit_id) ON DELETE CASCADE,
    path ltree
);
DROP CAST IF EXISTS (character varying AS ltree);
CREATE CAST (character varying AS ltree) WITH INOUT AS ASSIGNMENT;

DROP CAST IF EXISTS (TEXT AS ltree);
CREATE CAST (TEXT AS ltree) WITH INOUT AS ASSIGNMENT;

CREATE UNIQUE INDEX IF NOT EXISTS tree_node_id_index ON shop_unit_tree(node_id);
CREATE INDEX IF NOT EXISTS tree_path_index ON shop_unit_tree USING gist(path);

-- -----------------------------------------------------
-- Table "archive_shop_unit"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS archive_shop_unit (
    archive_shop_unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_unit_id BIGINT NOT NULL REFERENCES shop_unit(shop_unit_id) ON DELETE CASCADE,
    id UUID,
    name VARCHAR(1024) NOT NULL,
    date TIMESTAMP NOT NULL,
    parent_id UUID,
    unit_type shop_unit_type NOT NULL,
    price BIGINT
);
CREATE INDEX IF NOT EXISTS archive_shop_unit_index_id ON archive_shop_unit(id);