-- -----------------------------------------------------
-- Enum type "shop_unit_type"
-- -----------------------------------------------------
CREATE TYPE shop_unit_type AS ENUM('OFFER', 'CATEGORY');
CREATE CAST (character varying AS shop_unit_type) WITH INOUT AS ASSIGNMENT;

-- -----------------------------------------------------
-- Table "shop_unit"
-- -----------------------------------------------------
CREATE TABLE shop_unit (
    shop_unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id UUID UNIQUE,
    name VARCHAR(1024) NOT NULL,
    date TIMESTAMP NOT NULL,
    parent_id UUID,
    shop_unit_parent_id BIGINT REFERENCES shop_unit(shop_unit_id) ON DELETE CASCADE,
    unit_type shop_unit_type NOT NULL,
    price BIGINT
    );
CREATE UNIQUE INDEX shop_unit_index_id ON shop_unit(id);

-- -----------------------------------------------------
-- Extension for tree in PostgreSQL
-- -----------------------------------------------------
CREATE EXTENSION IF NOT EXISTS ltree;

-- -----------------------------------------------------
-- Table "shop_unit_tree"
-- -----------------------------------------------------
CREATE TABLE shop_unit_tree (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id BIGINT REFERENCES shop_unit(shop_unit_id) ON DELETE CASCADE,
    path ltree
);
CREATE CAST (character varying AS ltree) WITH INOUT AS ASSIGNMENT;
CREATE CAST (TEXT AS ltree) WITH INOUT AS ASSIGNMENT;

CREATE UNIQUE INDEX tree_node_id_index ON shop_unit_tree(node_id);
CREATE INDEX tree_path_index ON shop_unit_tree USING gist(path);

-- -----------------------------------------------------
-- Table "archive_shop_unit"
-- -----------------------------------------------------
CREATE TABLE archive_shop_unit (
    archive_shop_unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_unit_id BIGINT NOT NULL REFERENCES shop_unit(shop_unit_id) ON DELETE CASCADE,
    id UUID,
    name VARCHAR(1024) NOT NULL,
    date TIMESTAMP NOT NULL,
    parent_id UUID,
    unit_type shop_unit_type NOT NULL,
    price BIGINT
);
CREATE INDEX archive_shop_unit_index_id ON archive_shop_unit(id);